[package]
name = "cobs"
version = "0.1.1"
authors = ["Allen Welkie <>"]
license = "MIT"
description = """
    This is an implementation of the Consistent Overhead Byte Stuffing (COBS) algorithm.
    COBS is an algorithm for transforming a message into an encoding where a specific value
    (the "sentinel" value) is not used. This value can then be used to mark frame boundaries
    in a serial communication channel. """
repository = "https://github.com/awelkie/cobs.rs"
keywords = ["consistent", "overhead", "byte", "stuffing"]

[dev-dependencies]
quickcheck = "*"
